Restructured how files are saved in tarballs, more compression options, cpu management

diff --git a/prj-diff b/prj-diff
--- a/prj-diff
+++ b/prj-diff
@@ -4,10 +4,10 @@
 set -euo pipefail
 
 CMD=$(prj-private-cli.py "$(basename $0)" "$@" <<EOF
-short="-b", long="--base", dest="BASE", type="str", default=".", help="Which base directory to use"
+short="-b", long="--base", dest="BASE", type="str", default="", help="Which base directory to use"
 long="--all", dest="ALL", type="FLAG", default=False, help="Ignore the .prjignore"
-short="-p", long="--backup", dest="BACKUP", type="str", default="", help="Which backup to compare to"
-short="-d", long="--dir", dest="DIR", type="str", default=".", help="Where to search for files"
+long="--cpus", dest="CPUS", type=int, default=2, help="What's the maximum number of CPUs we can use? Use -1 for all."
+dest="BACKUP", type="str", help="Which backup to compare to. Use HEAD to compare with latest. Use ALL to show all tracked files in the project."
 dest="TARGET", type=str, nargs="*", help="Only check these files"
 EOF
 )
@@ -22,51 +22,81 @@ fi
 
 eval "${CMD}"
 
-DIR=$(realpath "${DIR}" | sed 's/\/$//')
-
-BASE="$(prj-private-findbase.sh ${BASE})"
-
-source "${BASE}/.prj"
-if [ -z "${BACKUP:-}" ]
+EC=0
+if [ -z "${BASE:-}" ]
 then
-    BACKUP="${HEAD}"
-fi
-
-if [ -f "${BACKUP}" ]
-then
-    PREV_SHA="${BACKUP}"
-elif [ -z "${BACKUP}" ]
-then
-    PREV_SHA=""
+    BASE=$(prj-private-findbase.sh "${PWD}" 2> /dev/null) || EC="$?"
 else
-    PREV_SHA="${BASE}/${BKPDIR}/${BACKUP}.sha256"
+    BASE=$(prj-private-findbase.sh "${BASE}" True 2> /dev/null) || EC="$?"
 fi
 
+if [ "${EC}" -eq 2 ] && [ "${BACKUP:-}" != "HEAD" ]
+then
+    BKPDIR="${BASE}"
+elif [ "${EC}" -eq 0 ] && [ ! -z "${BASE:-}" ]
+then
+    source "${BASE}/.prj"
+    BKPDIR="${BASE}/${BACKUP_DIR}"
 
-if [ -z "${PREV_SHA:-}" ]
+    if [ -z "${BACKUP:-}" ] || [ "${BACKUP:-}" == "HEAD" ]
+    then
+        BACKUP="${HEAD}"
+    fi
+elif [ "${EC}" -ne 0 ]
 then
-    echo "Could not find backup file, printing new files"
-elif [ ! -f "${PREV_SHA:-}" ]
+    exit "${EC}"
+else
+    echo "ERROR: this shouldn't happen" >&2
+    exit 1
+fi
+
+if [ "${BACKUP}" == "HEAD" ]
 then
-    echo "ERROR: File '${PREV_SHA}' does not exist" >&2
+    echo "ERROR: Could not find a backup corresponding to HEAD" >&2
+    echo "ERROR: This could happen if you're outside a bkp project or you don't have any previous backups." >&2
+    echo "ERROR: Try providing the actual path to the sha256 sums" >&2
+    exit 1
+fi
+
+if [ -e "${BACKUP}" ]
+then
+    BACKUP_SHA="${BACKUP}"
+elif [ -e "${BKPDIR}/${BACKUP}.sha256" ]
+then
+    BACKUP_SHA="${BKPDIR}/${BACKUP}.sha256"
+elif [ "${BACKUP}" == "ALL" ]
+then
+    BACKUP_SHA=""
+else
+    echo "ERROR: could not find a backup corresponding to '${BACKUP}'" >&2
+    echo "ERROR: Try providing the actual path to the sha256 sums or use ALL to show all tracked files in project." >&2
+    exit 1
+fi
+
+if [ "${BACKUP}" == "ALL" ]
+then
+    BACKUP_SHA=""
+elif [ ! -f "${BACKUP_SHA:-}" ]
+then
+    echo "ERROR: File '${BACKUP_SHA}' does not exist" >&2
     exit 1
 elif [ "${#TARGET[@]}" -gt 0 ]
 then
-    PREV_SHA=$(
-        cat "${PREV_SHA}" \
+    BACKUP_SHA=$(
+        cat "${BACKUP_SHA}" \
         | grep \
           --line-regex \
           -f <(printf '[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*%s\n' "${TARGET[@]}")
     )
 else
-    PREV_SHA=$(cat "${PREV_SHA}")
+    BACKUP_SHA=$(cat "${BACKUP_SHA}")
 fi
 
 cd "${BASE}"
 
 [ "${ALL}" == "True" ] && ALL_FLAG="--all" || ALL_FLAG=""
 
-CHK=$(prj-sha ${ALL_FLAG} --base "${BASE}" --dir "${DIR}" "${TARGET[@]}")
+CHK=$(prj-sha ${ALL_FLAG} --cpus "${CPUS}" --base "${BASE}" "${TARGET[@]}")
 
 difference() {
     grep --invert-match --fixed-strings --line-regexp --file $2 $1 || :
@@ -76,5 +106,5 @@ intersection() {
     grep --fixed-strings --line-regexp --file $2 $1 || :
 }
 
-BKPDIFF="$((diff <(echo "${PREV_SHA}") <(echo "${CHK}") || :) | prj-private-diff.sh)"
-echo "${BKPDIFF}"
+BKPDIFF="$((diff <(echo "${BACKUP_SHA}" | sort) <(echo "${CHK}" | sort) || :) | prj-private-diff.sh)"
+echo "${BKPDIFF}" | (grep -v '^[[:space:]]*$' || :)
diff --git a/prj-find b/prj-find
--- a/prj-find
+++ b/prj-find
@@ -3,8 +3,8 @@
 set -euo pipefail
 
 CMD=$(prj-private-cli.py "$(basename $0)" "$@" <<EOF
-short="-b", long="--base", dest="BASE", type="str", default=".", help="Which base directory to use"
-dest="BACKUP", type="str", help="The backup to look for files in"
+short="-b", long="--base", dest="BASE", type="str", default="", help="Which base directory to use"
+dest="BACKUP", type="str", help="The backup to look for files in. Use HEAD to compare with latest. Use ALL to show all locations of all backup files."
 dest="TARGET", type=str, nargs="*", help="Only look for the locations of these files, not the whole snapshot"
 EOF
 )
@@ -19,36 +19,81 @@ fi
 
 eval "${CMD}"
 
-BASE="$(prj-private-findbase.sh ${BASE})"
-
-source "${BASE}/.prj"
-if [ "${BACKUP:-}" == "HEAD" ]
+BACKUP=$(echo "${BACKUP}" | (grep -v '^[[:space:]]*$' || :))
+if [ -z "${BACKUP}" ]
 then
-    BACKUP="${HEAD}"
+    echo "ERROR: BACKUP was an empty string. We need a value here." >2
+    exit 1
 fi
 
-if [ -f "${BACKUP}" ]
+EC=0
+if [ -z "${BASE:-}" ]
 then
-    PREV_SHA="${BACKUP%.tar.gz}.sha256"
+    BASE=$(prj-private-findbase.sh "${PWD}" 2> /dev/null) || EC="$?"
 else
-    BACKUP=$(basename "${BACKUP%.tar.gz}")
-    PREV_SHA="${BASE}/${BKPDIR}/${BACKUP}.sha256"
-    BACKUP="${BASE}/${BKPDIR}/${BACKUP}.tar.gz"
+    BASE=$(prj-private-findbase.sh "${BASE}" True 2> /dev/null) || EC="$?"
 fi
 
-if [ -z "${BACKUP:-}" ] || [ ! -f "${BACKUP:-}" ]
+if [ "${EC}" -eq 2 ] && [ "${BACKUP:-}" != "HEAD" ]
 then
-    echo "ERROR: The backup file ${BACKUP} does not exist." >&2
+    BKPDIR="${BASE}"
+elif [ "${EC}" -eq 0 ] && [ ! -z "${BASE:-}" ]
+then
+    source "${BASE}/.prj"
+    BKPDIR="${BASE}/${BACKUP_DIR}"
+
+    if [ -z "${BACKUP:-}" ] || [ "${BACKUP:-}" == "HEAD" ]
+    then
+        BACKUP="${HEAD}"
+    fi
+elif [ "${EC}" -ne 0 ]
+then
+    exit "${EC}"
+else
+    echo "ERROR: this shouldn't happen" >&2
     exit 1
 fi
 
-if [ -z "${PREV_SHA:-}" ] || [ ! -f "${PREV_SHA:-}" ]
+if [ "${BACKUP}" == "HEAD" ]
 then
-    echo "ERROR: Could not find sha file for the backup file ${BACKUP}." >&2
+    echo "ERROR: Could not find a backup corresponding to head" >&2
+    echo "ERROR: This could happen if you're outside a bkp project or you don't have any previous backups." >&2
+    echo "ERROR: Try providing the actual path to the sha256 sums" >&2
     exit 1
 fi
 
-TARGET_SHAS=$(sed 's/[[:space:]][[:space:]]*/\t/' "${PREV_SHA}" | awk -F'\t' 'BEGIN {OFS="\t"} {print $2, $1}')
+if [ -e "${BACKUP}" ]
+then
+    SHAS=( "${BACKUP}" )
+elif [ -e "${BKPDIR}/${BACKUP}.sha256" ]
+then
+    SHAS=( "${BKPDIR}/${BACKUP}.sha256" )
+elif [ "${BACKUP}" == "ALL" ]
+then
+    S=$(find "${BKPDIR}" -name "*.sha256" )
+    if [ -z "${S}" ]
+    then
+        echo "ERROR: You specified 'ALL', but we couldn't find any .sha256 files in your backup directory." >&2
+        echo "ERROR: Make sure that you are in a prj project or --base is specified correctly" >&2
+        exit 1
+    fi
+
+    readarray -t SHAS < <(echo "${S}")
+else
+    echo "ERROR: This shouldn't happen, contact the authors." >&2
+    exit 1
+fi
+
+for SHA in "${SHAS[@]}"
+do
+    if [ -z "${SHA:-}" ] || [ ! -e "${SHA:-}" ]
+    then
+        echo "ERROR: The backup file ${SHA:-${BACKUP}} does not exist." >&2
+        exit 1
+    fi
+done
+
+TARGET_SHAS=$(cat "${SHAS[@]}" | sed 's/[[:space:]][[:space:]]*/\t/' | sort -u)
 
 # Deals with case of empty strings
 if [ "${#TARGET[@]}" -gt 0 ]
@@ -56,41 +101,43 @@ then
     readarray -t TARGET < <(prj-private-relpaths.sh "${BASE}" "${TARGET[@]}")
 fi
 
+# CD after getting new target paths to allow relative paths in command
+cd "${BASE}"
+
 if [ "${#TARGET[@]}" -gt 0 ]
 then
-    TARGET_SHAS=$(echo "${TARGET_SHAS}" | grep -f <(printf '^%s[[:space:]][A-Za-z0-9][A-Za-z0-9]*$\n' "${TARGET[@]}"))
+    TARGET_SHAS=$(echo "${TARGET_SHAS}" \
+        | (grep -v '^[[:space:]]*$' || :) \
+        | (grep -f <(printf '^[A-Za-z0-9][A-Za-z0-9]*[[:space:]]%s$\n' "${TARGET[@]}") || :))
 fi
 
+TARFILES=$(find "${BKPDIR}" -name "*.tar")
 
-BACKUPS=$(ls "${BASE}/${BKPDIR}/"*.tar.gz | awk -v BKP="${BACKUP}" '$0 <= BKP' | sort -r | tr '\0' 'X')
+if [ -z "${TARFILES}" ]
+then
+    echo "${TARGET_SHAS}" | sed 's/^/MISSING\t/ ; s/$/\tNA/'
+    exit 0
+fi
 
-echo "${TARGET_SHAS}" | while read LINE
+MANIFESTS=( )
+while read -u 3 TARFILE
 do
-    TARGET_FILE=$(echo "${LINE}" | cut -d'	' -f 1)
-    TARGET_SHA=$(echo "${LINE}" | cut -d'	' -f 2)
-
-    export GOTIT=
-    while read BKP
-    do
-        TARFILE_LINE=$(prj-tarlist --base "${BASE}" "${BKP}" "${TARGET_FILE}") || :
-
-        if [ ! -z "${TARFILE_LINE}" ]
-        then
-            TARFILE_BKP=$(echo "${TARFILE_LINE}" | cut -d'	' -f 1)
-            TARFILE_SHA=$(echo "${TARFILE_LINE}" | cut -d'	' -f 3)
-            if [[ "${TARFILE_SHA}" == "${TARGET_SHA}" ]]
-            then
-                export GOTIT="${TARFILE_BKP}"
-                break
-            fi
-        fi
-    done <<< "${BACKUPS}"
-    # Using heredoc style needed to avoid subshell, causing GOTIT to remain unset
-
-    if [ -z "${GOTIT}" ]
+    MANIFEST="${TARFILE%%.tar}.MANIFEST"
+    if [ ! -s "${MANIFEST}" ]
     then
-        echo "WARNING: could not find file corresponding to ${TARGET_FILE} with ${TARGET_SHA}" >&2
-    else
-        echo -e "${GOTIT}\t${TARGET_FILE}\t${TARGET_SHA}"
+        prj-remanifest "${TARFILE}"
     fi
-done
+    MANIFESTS+=( "${MANIFEST}" )
+done 3<<< "${TARFILES}"
+
+INNERFILES=$(cat "${MANIFESTS[@]}" | awk -F "\t" 'BEGIN {OFS="\t"} {print $2, $3, $1}')
+JOINED=$(
+    join -t'	' --check-order -a 2 -j 1 -e "MISSING" -o '1.3	2.1	2.2	1.2' \
+      <(echo -e "${INNERFILES}" | sort -u -k 1b,1) \
+      <(echo -e "${TARGET_SHAS}" | sort -u -k 1b,1) \
+    | awk -F"\t" 'BEGIN {OFS="\t"} $4 == "MISSING" {$4 = "NA"; print} {print}' \
+    | (grep -v '^[[:space:]]*$' || :) \
+    | sort -u
+)
+
+echo -e "${JOINED}"
diff --git a/prj-init b/prj-init
--- a/prj-init
+++ b/prj-init
@@ -10,10 +10,12 @@ long="--outputdir", dest="OUTPUTDIR", type="str", default="output", help="Where 
 long="--codedir", dest="CODEDIR", type="str", default="code", help="Where to store code"
 long="--envdir", dest="ENVDIR", type="str", default="envs", help="Where to store environments"
 long="--workdir", dest="WORKDIR", type="str", default="work", help="Where to working data"
-short="-c", long="--changelog", dest="CHANGELOG", type="str", default="", help="Where to store logs."
+long="--changelog", dest="CHANGELOG", type="str", default="", help="Where to store logs."
 long="--notefile", dest="NOTEFILE", type="str", default="", help="Where to cache notes to be saved later."
 long="--inputfile", dest="INPUTFILE", type="str", default="", help="Where to log the locations of inputs."
 long="--profile", dest="PRJPROFILE", type="str", default="project", choices=["project", "backup"], help="Where to cache notes to be saved later."
+short="-c", long="--compression", dest="COMPRESSION", type="str", default="gzip", choices=["gzip", "bzip2", "zstd"], help="Which compression algorithm to use when archiving files. Note that these tools will be needed for future decompression, so choose wisely."
+short="-l", long="--compression-level", dest="COMP_LEVEL", type="str", default="", help="Use this compression level instead of the program default. Integer"
 short="-m", long="--message", dest="MESSAGE", type="str", default="", help="The message to save"
 dest="BASE", type="str", default=".", nargs="?", help="Which base directory to use"
 EOF
@@ -38,6 +40,32 @@ then
     echo "ERROR: There is already a \`prj\` project in the specified folder '${BASE}'." >&2
     echo "If you really want to initialise here, you should remove \`.prj\` and \`.prjignore\`." >&2
     exit 1
+fi
+
+if [ "${COMPRESSION}" == "gzip" ]
+then
+    [ -z "${COMP_LEVEL:-}" ] && COMP_LEVEL=6
+    if [ "${COMP_LEVEL}" -lt 1 ] || [ "${COMP_LEVEL}" -gt 9 ]
+    then
+        echo "ERROR: compression levels for gzip must be between 1 and 9" >&2
+        exit 1
+    fi
+elif [ "${COMPRESSION}" == "bzip2" ]
+then
+    [ -z "${COMP_LEVEL:-}" ] && COMP_LEVEL=9
+    if [ "${COMP_LEVEL}" -lt 1 ] || [ "${COMP_LEVEL}" -gt 9 ]
+    then
+        echo "ERROR: compression levels for bzip2 must be between 1 and 9" >&2
+        exit 1
+    fi
+elif [ "${COMPRESSION}" == "zstd" ]
+then
+    [ -z "${COMP_LEVEL:-}" ] && COMP_LEVEL=19
+    if [ "${COMP_LEVEL}" -lt 1 ] || [ "${COMP_LEVEL}" -gt 19 ]
+    then
+        echo "ERROR: compression levels for zstd must be between 1 and 19" >&2
+        exit 1
+    fi
 fi
 
 mkdir -p ${BASE}
@@ -80,7 +108,13 @@ NOTEFILE="${NOTEFILE}"
 INPUTFILE="${INPUTFILE}"
 PRJPROFILE="${PRJPROFILE}"
 
-BKPDIR="${BKPDIR}"
+# Max size of each backup tar file in GB
+# Files bigger than this will be on their own :)
+MAXSIZE=4
+COMPRESSION="${COMPRESSION}"
+COMPRESSION_LEVEL="${COMP_LEVEL}"
+
+BACKUP_DIR="${BKPDIR}"
 INPUTDIR="${INPUTDIR}"
 OUTPUTDIR="${OUTPUTDIR}"
 WORKDIR="${WORKDIR}"
diff --git a/prj-restore b/prj-restore
--- a/prj-restore
+++ b/prj-restore
@@ -3,12 +3,14 @@
 set -euo pipefail
 
 CMD=$(prj-private-cli.py "$(basename $0)" "$@" <<EOF
-short="-b", long="--base", dest="BASE", type="str", default=".", help="Which base directory to use"
+short="-b", long="--base", dest="BASE_", type="str", default="", help="Which base directory to use"
 short="-m", long="--message", dest="MESSAGE", type="str", default="", help="The message to save"
 short="-d", long="--delete", dest="DELETE", type="FLAG", default=False, help="Delete files as well as overwriting them. Disabled if TARGET provided."
-short="-o", long="--outfile", dest="OUTFILE", type="str", default="", help="Where to write the logs. Note this will always append to existing files."
+long="--notefile", dest="NOTEFILE_", type="str", default="", help="Where to cache notes to be saved later."
 short="-y", long="--yes", dest="YES", type="FLAG", default=False, help="Don't confirm overwrites."
-dest="BACKUP", type="str", help="The backup to restore files from"
+long="--cpus", dest="CPUS", type=int, default=2, help="What's the maximum number of CPUs we can use? Use -1 for all."
+long="--tmp", dest="THISTMPDIR", type=str, default="", help="Where to store intermediate files. Default from TMPDIR or working directory."
+dest="BACKUP", type="str", help="The backup to restore files from. Use HEAD to restore from latest save."
 dest="TARGET", type=str, nargs="*", help="Only save these files"
 EOF
 )
@@ -23,18 +25,73 @@ fi
 
 eval "${CMD}"
 
-BASE="$(prj-private-findbase.sh ${BASE})"
-cd "${BASE}"
-
-source "${BASE}/.prj"
-DATE=$(date '+%Y%m%d-%H%M%S')
-if [ "${BACKUP:-}" == "HEAD" ]
+if [ ! -z "${THISTMPDIR:-}" ]
 then
-    BACKUP="${HEAD}"
+    TMPDIR="${THISTMPDIR}"
+elif [ -z "${TMPDIR:-}" ]
+then
+    TMPDIR="${PWD}"
 fi
 
-# NOTEFILE is set in .bkp
-[ -z "${OUTFILE:-}" ] && OUTFILE="${NOTEFILE}"
+EC=0
+if [ -z "${BASE_:-}" ]
+then
+    BASE="$(prj-private-findbase.sh "${PWD}" 2> /dev/null)" || EC="$?"
+else
+    BASE="$(prj-private-findbase.sh "${BASE_}" True 2> /dev/null)" || EC="$?"
+fi
+
+if [ "${EC}" -eq 2 ] && [ ! -z "${BASE_}"]
+then
+    BKPDIR="${BASE}"
+elif [ "${EC}" -eq 0 ] && [ ! -z "${BASE:-}" ]
+then
+    source "${BASE}/.prj"
+    BKPDIR="${BASE}/${BACKUP_DIR}"
+
+    if [ -z "${BACKUP:-}" ] || [ "${BACKUP:-}" == "HEAD" ]
+    then
+        BACKUP="${HEAD}"
+    fi
+elif [ "${EC}" -eq 2 ] && [ -z "${BASE_:-}" ]
+then
+    echo "WARNING: Couldn't find any 'prj' projects." >&2
+    echo "WARNING: If you use restore outside of a 'prj' product, you should specify the backup directory with --base." >&2
+    echo "WARNING: Will attempt to use current working directory as BASE dir." >&2
+    BKPDIR="${BASE}"
+elif [ "${EC}" -ne 0 ]
+then
+    exit "${EC}"
+else
+    echo "ERROR: this shouldn't happen" >&2
+    exit 1
+fi
+
+if [ "${BACKUP}" == "HEAD" ]
+then
+    echo "ERROR: Could not find a backup corresponding to HEAD" >&2
+    echo "ERROR: This could happen if you're outside a bkp project or you don't have any previous backups." >&2
+    echo "ERROR: Try providing the actual path to the sha256 sums" >&2
+    exit 1
+fi
+
+
+if [ -e "${BACKUP}" ]
+then
+    BACKUP_SHA="${BACKUP}"
+elif [ -e "${BKPDIR}/${BACKUP}.sha256" ]
+then
+    BACKUP_SHA="${BKPDIR}/${BACKUP}.sha256"
+else
+    echo "ERROR: could not find a backup corresponding to '${BACKUP}'" >&2
+    exit 1
+fi
+
+cd "${BASE}"
+
+DATE=$(date '+%Y%m%d-%H%M%S')
+NOTEFILE="${BASE}/${NOTEFILE_:-${NOTEFILE:-NOTES.txt}}"
+
 
 # Deals with case of empty strings
 if [ "${#TARGET[@]}" -gt 0 ]
@@ -47,20 +104,40 @@ then
     DELETE="False"
 fi
 
-FILES=$(prj-find --base "${BASE}" "${BACKUP}" "${TARGET[@]}")
+CHK=$(prj-sha --cpus "${CPUS}" --base "${BASE}" "${TARGET[@]}")
+BKPDIFF=$(
+    (diff <(sort "${BACKUP_SHA}") <(echo "${CHK}" | sort) || :) \
+        | prj-private-diff.sh \
+        | (grep -v '^[[:space:]]*$' || :)
+)
+readarray -t BKPFILES < <(echo "${BKPDIFF}" | awk '$1 != "NEW"' | cut -f 2)
+BKPFILES=$(prj-find --base "${BASE}" "${BACKUP}" "${BKPFILES[@]}")
+
+BKPDIFF=$(
+    join -t'	' -a 1 --check-order -1 2 -2 3 -e "MISSING" -o $'1.1\t1.2\t2.1\t2.2\t2.4' \
+        <(echo "${BKPDIFF}" | sort -u -k 2b,2) \
+        <(echo "${BKPFILES}" | sort -u -k 3b,3)
+)
+
+BKPDIFF=$(
+    join -t'	' -a 1 --check-order -1 2 -2 2 -e "MISSING" -o $'1.1\t1.2\t2.1\t1.3\t1.4\t1.5' \
+        <(echo "${BKPDIFF}" | sort -u -k 2b,2) \
+        <(echo "${CHK}" | sed 's/[[:space:]][[:space:]]*/\t/' | sort -u -k 2b,2)
+)
+# status filename currentchecksum tarfile bkpchecksum compression
+
+unset BKPFILES
 
 cleanup() {
     EC="$?"
     FN="$1"
-    BKPNAME="$2"
-    if [ "${EC}" -ne 0 ] && [ -f "${BKPNAME}" ]
+    TMPNAME="$2"
+    if [ "${EC}" -ne 0 ] && [ -f "${TMPNAME}" ]
     then
-        echo "ERROR: Encountered error so restoring original file ${FN}." >&2
-        echo -e "\nERROR: While extracting ${FN}, original retained" >> "${OUTFILE}"
-        mv "${BKPNAME}" "${FN}"
+        echo -e "\nERROR: While extracting ${FN}, original retained" >> "${NOTEFILE}"
     fi
 
-    rm -f "${BKPNAME}"
+    rm -f "${TMPNAME}"
     exit "${EC}"
 }
 
@@ -79,73 +156,81 @@ ask() {
     done
 }
 
-echo -e "\n## Restoring files from ${BACKUP} on ${DATE}" >> "${OUTFILE}"
-echo -e "\nExtracting files:" >> "${OUTFILE}"
+echo -e "\n## Restoring files from ${BACKUP} on ${DATE}" | tee --append "${NOTEFILE}"
+
+NEWMOD_FILES=$(echo "${BKPDIFF}" \
+    | awk 'BEGIN {OFS="\t"} $1 == "MODIFIED" {print} $1 == "DELETED" {$1="NEW"; print}' \
+    | (grep -v '^[[:space:]]*$' || :))
+DELETE_FILES=$(echo "${BKPDIFF}" \
+    | awk 'BEGIN {OFS="\t"} $1 == "NEW" {$1="DELETE"; print $1, $2, $3}' \
+    | (grep -v '^[[:space:]]*$' || :))
+
+if [ ! -z "${NEWMOD_FILES}" ]
+then
+    echo -e "\nExtracting files:" | tee --append "${NOTEFILE}"
+fi
 
 # -u 3 is needed here to allow user input from stdin in ask
 while read -u 3 LINE
 do
-    BKP=$(echo "${LINE}" | cut -d'	' -f 1)
+    if [ -z "${LINE}" ]
+    then
+        continue
+    fi
+
+    # status filename currentchecksum tarfile bkpchecksum compression
+    STATUS=$(echo "${LINE}" | cut -d'	' -f 1)
     FN=$(echo "${LINE}" | cut -d'	' -f 2)
     SHA=$(echo "${LINE}" | cut -d'	' -f 3)
-    TARNAME="${BASE}/${BKPDIR}/${BKP}.tar.gz"
+    TAR=$(echo "${LINE}" | cut -d'	' -f 4)
+    BKPSHA=$(echo "${LINE}" | cut -d'	' -f 5)
+    COMP=$(echo "${LINE}" | cut -d'	' -f 6)
 
-    BKPNAME="${FN}.bkp$$"
-    trap "cleanup '${FN}' '${BKPNAME}'" ERR
+    TARNAME="${BKPDIR}/${TAR}"
 
-    if [ ! -z "${FN}" ]
+    TMPFILE="${TMPDIR}/tmp-$(basename "${FN}")"
+    trap "cleanup '${FN}' '${TMPFILE}'" ERR
+
+    # We only ask permission if the file exists.
+    if [ "${YES}" == "False" ] && [ -f "${FN}" ]
     then
-        if [ -f "${FN}" ]
-        then
-            OLDSHA=$(sha256sum "${FN}" | cut -d' ' -f 1)
-            OP="MODIFIED"
-        else
-            OLDSHA=
-            OP="NEW"
-        fi
-
-        if [ -f "${FN}" ] && [ "${SHA}" == "${OLDSHA}" ]
-        then
-            echo "NOTE: Skipping '${FN}' as the checksums are the same."
-            echo "- SAME: ${FN} (sha: ${SHA})" >> "${OUTFILE}"
-            continue
-        fi
-
-        # We only ask permission if the file exists.
-        if [ "${YES}" == "False" ] && [ -f "${FN}" ]
-        then
-            ask "${FN}" "${TARNAME}" || continue
-        fi
-
-        if [ -f "${FN}" ]
-        then
-            mv "${FN}" "${BKPNAME}"
-        fi
-
-        tar --extract --gzip --file="${TARNAME}" "${FN}"
-        NEWSHA=$(sha256sum "${FN}" | cut -d' ' -f 1)
-
-        if [ "${SHA}" != "${NEWSHA}" ]
-        then
-            echo "ERROR: the extracted file '${FN}' from '${TARNAME}' doesn't match the expected checksum!" >&2
-            exit 1
-        else
-            rm -f "${BKPNAME}"
-        fi
-
-        [ -z "${OLDSHA}" ] && EXTRABIT="" || EXTRABIT="${OLDSHA} > "
-        echo "- ${OP}: ${FN} (sha: ${EXTRABIT}${SHA})" >> "${OUTFILE}"
+        ask "${FN}" "${TARNAME}" || continue
     fi
-done 3<<< "${FILES}"
 
+    if [ "${COMP}" == "uncompressed" ]
+    then
+        tar --extract --to-stdout --file="${TARNAME}" "${BKPSHA}" > "${TMPFILE}"
+    else
+        COMPTOOL=$(prj-private-getcomptool.sh decompress "${COMP}" 1 "${CPUS}")
+        tar --extract --to-stdout --file="${TARNAME}" "${BKPSHA}.${COMP}" \
+            | ${COMPTOOL} \
+            > "${TMPFILE}"
+    fi
+
+    NEWSHA=$(sha256sum "${TMPFILE}" | cut -d' ' -f 1)
+
+    if [ "${BKPSHA}" != "${NEWSHA}" ]
+    then
+        echo "ERROR: the extracted file '${FN}' from '${TARNAME}' doesn't match the expected checksum!" >&2
+        exit 1
+    else
+        mv "${TMPFILE}" "${FN}"
+        rm -f "${TMPFILE}"
+    fi
+
+    [ -z "${SHA}" ] && EXTRABIT="" || EXTRABIT="${SHA} > "
+    echo "- ${STATUS}: ${FN} (sha: ${EXTRABIT}${BKPSHA})" >> "${NOTEFILE}"
+done 3<<< "${NEWMOD_FILES}"
+# status filename currentchecksum tarfile bkpchecksum compressionext
 
 ask_delete() {
     FILES="$1"
     echo -e "\nYou specified --delete so we're removing files not in ${BACKUP}."
     echo -e "This will remove the following files:"
-    echo "${FILES}" | sed 's/^/- /'
+    echo "${FILES}" | awk '{printf("- %s (sha:%s)\n", $2, $3)}'
     while true
     do
+        echo
         read -p "Do you want to continue? [yn], use i to select individually. " RESPONSE
         case "${RESPONSE}" in
             [Yy]*) return 0; break;;
@@ -157,10 +242,12 @@ ask_delete() {
 }
 
 ask_indiv() {
-    FN="$1"
+    LINE="$1"
     while true
     do
-        read -p "Remove file '${FN}'? [yn] " RESPONSE
+        FN=$(echo "${LINE}" | cut -f 2)
+        SHA=$(echo "${LINE}" | cut -f 3)
+        read -p "Remove file '${FN}' (sha: ${SHA})? [yn] " RESPONSE
         case "${RESPONSE}" in
             [Yy]*) return 0; break;;
             [Nn]*) return 1; break;;
@@ -171,35 +258,23 @@ ask_indiv() {
 
 if [ "${DELETE}" == "True" ]
 then
-    BKPIGNORE=$(cat "${BASE}/.prjignore")
-    TODELETE=$(find "${BASE}" -type f,l | awk -v DIR="${BASE}" '{print substr($0, length(DIR) + 2)}')
 
-    if [ ! -z "${BKPIGNORE:-}" ] && [ ! -z "${TODELETE:-}" ]
+    if [ ! -z "${DELETE_FILES}" ]
     then
-        TODELETE=$(echo "${TODELETE}" | (grep --no-filename --invert-match -f <(echo "${BKPIGNORE}") || : ))
+        echo -e "\nDeleting files not present in ${BACKUP}:" >> "${NOTEFILE}"
     fi
 
-    if [ ! -z "${TODELETE:-}" ]
-    then
-        TODELETE=$(echo "${TODELETE}" | (grep --no-filename --invert-match -f <(echo "${FILES}" | cut -d'	' -f2) || : ) | (grep -v '^$' || :))
-    fi
-
-    if [ ! -z "${TODELETE}" ]
-    then
-        echo "1${TODELETE}1"
-        echo -e "\nDeleting files not present in ${BACKUP}:" >> "${OUTFILE}"
-    fi
-
-    if [ "${YES}" == "False" ] && [ ! -z "${TODELETE}" ]
+    if [ "${YES}" == "False" ] && [ ! -z "${DELETE_FILES}" ]
     then
         ASK_CODE=0
-        ask_delete "${TODELETE}" || ASK_CODE=$?
+        ask_delete "${DELETE_FILES}" || ASK_CODE=$?
 
         case "${ASK_CODE}" in
             0)
-                echo "${TODELETE}" \
+                echo "${DELETE_FILES}" \
+                    | cut -f 2 \
                     | xargs -I {} sh -c 'rm -f {} && echo "- DELETED: {}"' \
-                    >> "${OUTFILE}"
+                    | tee --append "${NOTEFILE}"
                 ;;
             1) : ;;
             2)
@@ -207,21 +282,23 @@ then
                 do
                     if ask_indiv "${LINE}"
                     then
-                        rm -f "${LINE}"
-                        echo "- DELETED: ${LINE}" >> "${OUTFILE}"
+                        FN=$(echo "${LINE}" | cut -f 2)
+                        rm -f "${FN}"
+                        echo "- DELETED: ${FN}" >> "${NOTEFILE}"
                     fi
-                done 4<<< "${TODELETE}"
+                done 4<<< "${DELETE_FILES}"
             ;;
         esac
     elif [ ! -z "${TODELETE}" ]
     then
         echo "${TODELETE}" \
+            | cut -f 2 \
             | xargs -I {} sh -c 'rm -f {} && echo "- DELETED: {}"' \
-            >> "${OUTFILE}"
+            | tee --append "${NOTEFILE}"
     else
         echo "NOTE: Didn't find any files to be deleted"
     fi
 fi
 
 
-echo -e "\nCompleted without error!" >> "${OUTFILE}"
+echo -e "\nCompleted without error!" | tee --append "${NOTEFILE}"
diff --git a/prj-save b/prj-save
--- a/prj-save
+++ b/prj-save
@@ -1,13 +1,20 @@
 #!/usr/bin/env bash
 
 # vi: ft=bash
+
 set -euo pipefail
 
 CMD=$(prj-private-cli.py "$(basename $0)" "$@" <<EOF
-short="-b", long="--base", dest="BASE", type="str", default=".", help="Which base directory to use"
+short="-b", long="--base", dest="BASE", type="str", default="", help="Which base directory to use"
 short="-m", long="--message", dest="MESSAGE", type="str", default="", help="The message to save"
 long="--all", dest="ALL", type="FLAG", default=False, help="Save everything, not just the diffs"
-short="-p", long="--backup", dest="BACKUP", type="str", default="", help="Which backup to compare to"
+long="--cpus", dest="CPUS", type=int, default=2, help="What's the maximum number of CPUs we can use? Use -1 for all."
+short="-c", long="--compression", dest="COMP", type="str", default="global", choices=["global", "gzip", "bzip2", "zstd"], help="Which compression algorithm to use when archiving files. Note that these tools will be needed for future decompression, so choose wisely."
+short="-l", long="--compression_level", dest="COMP_LEVEL", type="str", default="", help="Use this compression level instead of the program default."
+long="--notefile", dest="NOTEFILE_", type="str", default="", help="Where to cache notes to be saved later."
+long="--changelog", dest="CHANGELOG_", type="str", default="", help="Where to store logs."
+long="--tmp", dest="THISTMPDIR", type=str, default="", help="Where to store intermediate files. Default from TMPDIR or working directory."
+long="--bkpdir", dest="BKPDIR", type="str", default="", help="Which backup directory to use. Mandatory if you're not in a prj project. If specified you probably want this to be somewhere outside of your current working directory (or --base) to avoid backing up previous backups."
 dest="TARGET", type=str, nargs="*", help="Only save these files"
 EOF
 )
@@ -22,14 +29,59 @@ fi
 
 eval "${CMD}"
 
-BASE="$(prj-private-findbase.sh ${BASE})"
+if [ ! -z "${THISTMPDIR:-}" ]
+then
+    TMPDIR="${THISTMPDIR}"
+elif [ -z "${TMPDIR:-}" ]
+then
+    TMPDIR="${PWD}"
+fi
 
-source "${BASE}/.prj"
+EC=0
+if [ -z "${BASE:-}" ]
+then
+    BASE="$(prj-private-findbase.sh "${PWD}" 2> /dev/null)" || EC="$?"
+else
+    BASE="$(prj-private-findbase.sh "${BASE}" True 2> /dev/null)" || EC="$?"
+fi
+
+if [ "${EC}" -eq 2 ] && [ ! -z "${BKPDIR:-}" ]
+then
+    BKPDIR=$(realpath "${BKPDIR}")
+elif [ "${EC}" -eq 0 ] && [ ! -z "${BASE:-}" ]
+then
+    source "${BASE}/.prj"
+    [ -z "${BKPDIR}" ] && BKPDIR="${BASE}/${BACKUP_DIR}"
+elif [ "${EC}" -eq 2 ] && [ -z "${BKPDIR:-}" ]
+then
+    echo "ERROR: Couldn't find any 'prj' projects." >&2
+    echo "ERROR: If you use save outside of a 'prj' product, you must specify the backup directory to --bkpdir." >&2
+    exit 1
+elif [ "${EC}" -ne 0 ]
+then
+    exit "${EC}"
+else
+    echo "ERROR: this shouldn't happen" >&2
+    exit 1
+fi
+
+
 DATE=$(date '+%Y%m%d-%H%M%S')
-TARBALL="${BASE}/${BKPDIR}/${DATE}.tar.gz"
-SHAFILE="${BASE}/${BKPDIR}/${DATE}.sha256"
-CHANGELOG="${BASE}/${CHANGELOG}"
-NOTEFILE="${BASE}/${NOTEFILE}"
+MAX_TAR_SIZE=50000  #$(( "${MAXSIZE:-4}" * 1000000 ))
+SHAFILE="${BKPDIR}/${DATE}.sha256"
+CHANGELOG_BNAME="${CHANGELOG_:-${CHANGELOG:-CHANGELOG.txt}}"
+CHANGELOG="${BASE}/${CHANGELOG_BNAME}"
+NOTEFILE="${BASE}/${NOTEFILE_:-${NOTEFILE:-NOTES.txt}}"
+
+[ "${COMP:-}" == "global" ] && COMP="${COMPRESSION:-gzip}"
+[ -z "${COMP_LEVEL:-}" ] && COMP_LEVEL="${COMPRESSION_LEVEL:-6}"
+COMP_COMMAND=$(prj-private-getcomptool.sh compress "${COMP}" "${COMP_LEVEL}" ${CPUS})
+
+case "${COMP}" in
+    gzip) COMP_EXT="gz";;
+    bzip2) COMP_EXT="bz2";;
+    zstd) COMP_EXT="zst";;
+esac
 
 if [ -s "${NOTEFILE}" ]
 then
@@ -38,9 +90,8 @@ else
     NOTES=""
 fi
 
-
 [ "${ALL}" == "True" ] && ALL_FLAG="--all" || ALL_FLAG=""
-CHK=$(prj-sha ${ALL_FLAG} --base "${BASE}" --dir "${BASE}" "${TARGET[@]}")
+CHK=$(prj-sha ${ALL_FLAG} --cpus "${CPUS}" --base "${BASE}" "${TARGET[@]}")
 
 if [ -z "${CHK:-}" ]
 then
@@ -48,107 +99,91 @@ then
     exit 0
 fi
 
-difference() {
-    grep --invert-match --fixed-strings --line-regexp --file $2 $1 || :
+already_compressed() {
+    FN="${1,,}" # lowecase
+    EXT="${FN##*.}"
+    # Using case just makes it easier to write lots of extensions
+    case "${EXT}" in
+        jpg|jpeg) return 0;;
+        gz|gzip|tgz|xz|txz|bzip|bz|bzip2|bz2|tbz|tbz2|zst|zl|zz|lzma|tlzma|tlz|lz|lz4|sfs|z) return 0;;
+        7z|zip|rar) return 0;;
+        deb|rpm|sif|jar|pkg) return 0;;
+        h5|hdf5|npz|parquet|bam|ubam|cram|ucram|bcf|og|vg|xg|gcsa|gam) return 0;;
+        *) return 1;;
+    esac
 }
-
-intersection() {
-    grep --fixed-strings --line-regexp --file $2 $1 || :
-}
-
-if [ -z "${BACKUP:-}" ]
-then
-    BACKUP="${HEAD}"
-fi
-
-if [ -z "${BACKUP:-}" ]
-then
-    PREV_SHA=""
-elif [ -f $(realpath "${BACKUP}" 2> /dev/null || :) ]
-then
-    PREV_SHA=$(realpath "${BACKUP}")
-else
-    PREV_SHA="${BASE}/${BKPDIR}/${HEAD}.sha256"
-    if [ ! -f "${PREV_SHA:-}" ]
-    then
-        echo "ERROR: File '${PREV_SHA}' does not exist"
-        exit 1
-    fi
-fi
 
 # Important to cd before tar so that it decompresses properly
 cd "${BASE}"
 
-CHG=""
+find_next_number() {
+    BACKUPDIR="$1"
+    TF=$(find "${BACKUPDIR}" \
+        -name "*.tar" \
+        -printf '%f\n')
 
-if [ -z "${BACKUP:-}" ]
-then
-    echo "${CHK}" > "${SHAFILE}"
-    FILES="$(echo "${CHK}" | cut -d' ' -f 3-)"
-    if [ "${#TARGET[@]}" -gt 0 ]
+    if [ -z "${TF:-}" ]
     then
-        FILES=$(intersection <(printf '%s\n' "${TARGET[@]}") <(echo "${FILES}"))
-    fi
-
-    CHG+="\n## ${DATE}\n"
-    CHG+="\nNew backup set:\n"
-    CHG+=$(echo "${FILES}" | sed 's/^/- NEW: /')
-    CHG+="\n"
-
-else
-    if [ "${#TARGET[@]}" -gt 0 ]
-    then
-        PREV_SHA=$(
-            cat "${PREV_SHA}" \
-            | grep \
-              --line-regex \
-              -f <(printf '[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*%s\n' "${TARGET[@]}")
-        )
+        echo 0000
     else
-        PREV_SHA=$(cat "${PREV_SHA}")
+        echo "${TF}" \
+            | sed 's/^bkp-\([[:digit:]][[:digit:]]*\)\.tar$/\1/' \
+            | awk 'BEGIN {i=1} {if ($0 > i) {i=$0}} END {printf("%04d\n", i + 1)}'
     fi
+}
 
-    BKPDIFF="$((diff <(echo "${PREV_SHA}") <(echo "${CHK}") || :) | prj-private-diff.sh)"
+get_best_archive() {
+    BACKUPDIR="$1"
+    MAX_SIZE="$2"
+    FILE_SIZE="$3"
 
-    if [ "${ALL}" == "True" ]
+    TF=$(find "${BACKUPDIR}" \
+        -name "*.tar" \
+        -printf '%f\t%s\n')
+
+    if [ -z "${TF:-}" ]
     then
-        FILES="$(echo "${CHK}" | cut -d' ' -f 3-)"
+        echo "${BACKUPDIR}/bkp-0000.tar"
     else
-        FILES="$(echo "${BKPDIFF}" | ( grep -v "^DELETED" || : ) | cut -d'	' -f 2-)"
-    fi
+        NEXT=$(echo "${TF}" | awk -v MAX="${MAX_SIZE}" -v FS="${FILE_SIZE}" -F"\t" '
+            BEGIN { best="new"; best_size="" }
+            (FS + $2) <= MAX { s=FS + $2; if (s > best_size) {best=$1; best_size=s} }
+            END {print best}
+        ')
 
-    if [ "${#TARGET[@]}" -gt 0 ]
-    then
-        FILES=$(intersection <(echo "${FILES}") <(printf '%s\n' "${TARGET[@]}"))
-    fi
-
-    if [ -z "${FILES:-}" ]
-    then
-        echo "No changes to be saved!"
-        exit 0
-    fi
-
-    CHG+="\n\n## ${DATE}\n"
-
-    if [ ! -z "${BKPDIFF}" ]
-    then
-        CHG+="\nModified files:\n"
-        CHG+=$(echo "${BKPDIFF}" | sed 's/^/- /' | sed 's/\t/: /')
-        CHG+="\n"
-    fi
-
-    if [ "${ALL}" == "True" ]
-    then
-        COPIED=$(difference <(echo "${FILES:-}") <(echo "${BKPDIFF}" | cut -f2))
-
-        if [ ! -z "${COPIED}" ]
+        if [ "${NEXT}" == "new" ]
         then
-            CHG+="\nCopying unmodified files as --all option was given\n"
-            CHG+="\nCopied files:\n"
-            CHG+=$(echo "${COPIED}" | sed 's/^/- /')
-            CHG+="\n"
+            NUM=$(find_next_number "${BACKUPDIR}")
+            NEXT="bkp-${NUM}.tar"
         fi
+        echo "${BACKUPDIR}/${NEXT}"
     fi
+}
+
+TARGET_FILES=$(prj-find --base "${BASE}" <(echo "${CHK}") "${TARGET[@]}")
+UNBACKEDUP_FILES=$(echo "${TARGET_FILES}" | awk -v CHG="${CHANGELOG_BNAME}" '($1 == "MISSING") && ($3 != CHG)' )
+
+if [ -z "${TARGET_FILES:-}" ]
+then
+    echo "ERROR: No changes since last backup! Exiting without doing anything" >&2
+    exit 1
+fi
+
+if [ -f "${CHANGELOG}" ]
+then
+    CHG="\n\n"
+else
+    CHG=""
+fi
+
+CHG+="## BACKUP: ${DATE}\n"
+echo -e "## SAVE: Creating new backup ${DATE}\n"
+
+if [ -z "${UNBACKEDUP_FILES}" ]
+then
+    S="NOTE: there are no new files to add, so this will just save the changelog and a snapshot file."
+    echo "${S}"
+    CHG+="\n${S}\n"
 fi
 
 if [ ! -z "${MESSAGE:-}" ]
@@ -156,15 +191,58 @@ then
     CHG+="\n${MESSAGE}"
 fi
 
-CHGLOG_ORIG=$(cat "${CHANGELOG}")
-cleanup_err() {
-    # Remove any updates if it failed
-    echo "${CHGLOG_ORIG}" > "${CHANGELOG}"
-    rm -f '${TARBALL}' '${TARBALL}.sha256' '${SHAFILE}'
-    exit 1
+write_to_tar() {
+    BACKUPDIR="$1"
+    SHA="$2"
+    FN="$3"
+    FN_SIZE="$4"
+    SHOULDCOMPRESS="${5:-True}"
+
+    TAR=$(get_best_archive "${BACKUPDIR}" "${MAX_TAR_SIZE}" "${FN_SIZE}")
+    MANIFEST="${TAR%.tar}.MANIFEST"
+
+    if [ -f "${TAR}" ]
+    then
+        MODE="--append"
+    else
+        MODE="--create"
+    fi
+
+    if (already_compressed "${FN}") || [ "${SHOULDCOMPRESS}" == "False" ]
+    then
+        OFN="${SHA}"
+        echo "Adding '${FN}' to '${TAR}'"
+        tar --transform "s#${FN}#${OFN}#" ${MODE} --file "${TAR}" "${FN}"
+        echo -e "$(basename "${TAR}")\t${SHA}\tuncompressed" >> "${MANIFEST}"
+    else
+        OFN="${SHA}.${COMP_EXT}"
+        echo "Compressing '${FN}'"
+        cleanup(){ EC="$?"; rm -f "${TMPDIR:-${BASE}}/${OFN}"; exit "${EC}"; }
+        trap cleanup ERR
+        ${COMP_COMMAND} "${FN}" > "${TMPDIR:-${BASE}}/${OFN}"
+        echo "Adding '${FN}' to '${TAR}'"
+        cd "${TMPDIR:-${BASE}}"
+        tar ${MODE} --file "${TAR}" "${OFN}"
+        rm -f "${TMPDIR:-${BASE}}/${OFN}"
+        cd "${BASE}"
+        echo -e "$(basename "${TAR}")\t${SHA}\t${COMP_EXT}" >> "${MANIFEST}"
+    fi
+    CHG+="\n- Copied '${FN}' as '${OFN}' to '${TAR}'"
 }
 
-trap cleanup_err ERR
+if [ ! -z "${UNBACKEDUP_FILES}" ]
+then
+    CHG+="\nAdding new files:"
+
+    while read -u 4 LINE
+    do
+        SHA=$(echo "${LINE}" | cut -d'	' -f 2)
+        FN=$(echo "${LINE}" | cut -d'	' -f 3)
+        FN_SIZE=$(find $(dirname "${FN}") -name $(basename "${FN}") -printf "%s\n")
+        write_to_tar "${BKPDIR}" "${SHA}" "${FN}" "${FN_SIZE}"
+    done 4<<< "${UNBACKEDUP_FILES}"
+fi
+
 
 if [ ! -z "${NOTES}" ]
 then
@@ -172,25 +250,52 @@ then
     CHG+="\n${NOTES}"
 fi
 
+if [ -e "${CHANGELOG}" ]
+then
+    CHGLOG_ORIG=$(cat "${CHANGELOG}")
+else
+    CHGLOG_ORIG=""
+fi
+
+if [ -e "${NOTEFILE}" ]
+then
+    NOTEFILE_ORIG=$(cat "${NOTEFILE}")
+else
+    NOTEFILE_ORIG=""
+fi
+
+cleanup_err() {
+    EC="$?"
+    # Remove any updates if it failed
+    [ ! -z "${CHGLOG_ORIG}" ] && (echo "${CHGLOG_ORIG}" > "${CHANGELOG}")
+    [ ! -z "${NOTEFILE_ORIG:-}" ] && (echo "${NOTEFILE_ORIG}" > "${NOTEFILE}")
+    rm -f "${SHAFILE}"
+    exit "${EC}"
+}
+
+trap cleanup_err ERR
 echo -e "${CHG}" >> "${CHANGELOG}"
+rm -f "${NOTEFILE}"
 
 # Update the SHASUM for the changelog file
 CHGLOG_BNAME=$(echo "${CHANGELOG}" | awk -v DIR="${BASE}" '{print substr($0, length(DIR) + 2)}')
-CHGLOG_SHA=$(prj-sha --base "${BASE}" --dir "${BASE}" "${CHGLOG_BNAME}")
-echo "${CHK}" | sed "s#^.*${CHGLOG_BNAME}\$#${CHGLOG_SHA}#" > "${SHAFILE}"
+CHGLOG_SHA=$(prj-sha --base "${BASE}" "${CHGLOG_BNAME}" | cut -d' ' -f 1)
+TARGET_FILES=$(prj-find --base "${BASE}" <(echo -e "${CHGLOG_SHA}  ${CHGLOG_BNAME}"))
+UNBACKEDUP_FILES=$(echo "${TARGET_FILES}" | awk '$1 == "MISSING"')
 
-# The updated changelog should be in the backup
-# If CHGLOG_SHA is not empty, then it's not in prjignore
-if [ ! -z "${CHGLOG_SHA:-}" ]
+if [ ! -z "${UNBACKEDUP_FILES}" ]
 then
-    FILES+="\n$(basename "${CHANGELOG}")"
+    CHGLOG_SIZE=$(find $(dirname "${CHGLOG_BNAME}") -name $(basename "${CHGLOG_BNAME}") -printf "%s\n")
+    write_to_tar "${BKPDIR}" "${CHGLOG_SHA}" "${CHGLOG_BNAME}" "${CHGLOG_SIZE}" "False"
 fi
 
-echo "Creating backup with files:"
-# grep and sort removes empty lines and duplicates
-tar --create --gzip -vv --file "${TARBALL}" --files-from=<(echo -e "${FILES}" | (grep -v '^$' || :) | sort -u)
-sha256sum "${TARBALL}" > "${TARBALL}.sha256"
+echo "${CHK}" | (grep -v "${CHGLOG_BNAME}\$" || : ; echo "${CHGLOG_SHA}  ${CHGLOG_BNAME}") > "${SHAFILE}"
 
-rm -f "${NOTEFILE}"
+cd $(dirname "${SHAFILE}")
+
+SHAFILE_BNAME=$(basename "${SHAFILE}")
+SHAFILE_SIZE=$(find . -name "${SHAFILE_BNAME}" -printf "%s\n")
+write_to_tar "${BKPDIR}" "${SHAFILE_BNAME}" "${SHAFILE_BNAME}" "${SHAFILE_SIZE}" "False"
+
 
 sed -i "/^HEAD/s/^.*\$/HEAD=${DATE}/" "${BASE}/.prj"
